version: '3.9'

services:
  
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass 1234
    ports: 
      - "6379:6379"
    networks:
      - emergencias
  
  db:
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: BackArqui
    ports:
      - '5432:5432'
    networks:
      - emergencias

  conexion:
    build: ./Conexion
    environment:
      DATABASE_HOST: db
    command: ruby conexion.rb
    volumes:
      - ./Conexion:/conexion
    networks:
      - emergencias
    container_name: conexion
    depends_on:
      - db

  api:
    build: ./backArqui
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3333 -b '0.0.0.0'"
    volumes:
      - ./backArqui:/app
    networks:
      - emergencias
    container_name: api
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
      REDIS_PASSWORD: password
      

volumes:
  postgres:

networks: 
  emergencias:
    driver: bridge